### ISSUE TITLE
Should we unify our efforts?

### ISSUE THREAD

**Issue by skuro** [zwz/plantuml-mode#8]
Hi,

I'm the maintainer of [`puml-mode`][puml], yet another fork of your original work. I see that development is active on both our projects and there's no apparent reason to keep the codebases separate, while the [`plantuml-mode` project][other-plantuml] downloadable [from MELPA][plantuml-melpa] isn't receiving any commit since more than 2 years ago.

It would be better, in my opinion, if we concentrated our efforts in a single place. I'd like discuss here with you how to make this happen, having one single authoritative `plantuml-mode` package in the Emacs ecosystem.

To start off, here's my current point of view on the subject:

- we should choose one single repo in which to jointly continue development
- we should select and merge the features available in both codebases
- I have no particular interest into which one we choose, who's the maintainer, etc.
- features which are IMHO unique to `puml-mode` are better docs, MELPA integration, SVG / PNG preview

Looking forward to hearing your opinion on the subject.

[puml]: https://github.com/skuro/puml-mode
[other-plantuml]: https://github.com/wildsoul/plantuml-mode
[plantuml-melpa]: http://melpa.org/#/plantuml-mode

**Comment by pwojnowski** [comment]
Great idea! Please join into one project, so that others could contribute too. Now it is very confusing.

**Comment by nicbet** [comment]
+1

**Comment by zwz** [comment]
@skuro 
I totally agree with you.
I was busy for last several months, and I think it is better you be the maintainer.
However, the name "plantuml-mode" is clearer.
What do you think?

**Comment by skuro** [comment]
@zwz, fine with me, and I actually totally agree with you. I changed name just not to collide with your project, but `plantuml-mode` is the only one that makes sense.

To proceed with the merge, I will need to look at the codebases and spot differences and how to merge them.

We also need to figure out how to manage the [melpa](http://melpa.org/#/plantuml-mode) side of things and update [the recipe](https://github.com/melpa/melpa/blob/master/recipes/plantuml-mode).

Stay tuned..

**Comment by skuro** [comment]
I created a [new issue](https://github.com/skuro/puml-mode/issues/26) and a [new branch](https://github.com/skuro/puml-mode/tree/feature/merge-repositories) to track the merge efforts. Feel free to contribute!

For the time being, I'll just close the issue here.
